name: Publish Container

on: 
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: dungdt-netapi-azure-docker  
  AZURE_ACR_NAME: dungdtacr 
  IMAGE_NAME: netapi-azure-docker 
  AZURE_ACR_LOGIN_SERVER: dungdtacr.azurecr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Login to ACR'
        uses: azure/docker-login@v1
        with:
            login-server: ${{ env.AZURE_ACR_LOGIN_SERVER }}
            username: ${{ env.AZURE_ACR_NAME }}
            password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest .

      # Push Docker image to ACR
      - name: Push Docker image to ACR
        run: docker push ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{ env.AZURE_ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
